---
output  :
  aliases: {}
  format: markdown
  options:
    tablefmt: pipe # see https://pypi.org/project/tabulate/
    stralign: center
    colalign:
      - right
      - center
timespan: now-14d/d - now UTC
pattern : (?<=Co-authored-by:\s)[^<\n]+<.*>
clients : []
