---
output :
  map_emails_to_aliases:
    joy.joysen@example.com: joy
    jil.jonsen@example.com: jil
    jim.jonsen@example.com: jim
clients:
  # github repositories options - see https://github.com/PyGithub/PyGithub/blob/master/github/MainClass.py#L112
  - api: github
    options:
      login_or_token: '{{ .Env.ACCESS_TOKEN_GITHUB }}'
    # repos is expected to be either literal "*" or a list of strings.
    # if first and last character of a string is "/" it is treated as regular expression
    repos:
      - /^pairing_.*/
  # gitlab repositories options - see https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/__init__.py#L51
  #  - api: gitlab
  #    base_url: ...
  #    access_token: '{{ .Env.ACCESS_TOKEN_GITLAB }}'
