---
apis:
  # github repositories options - see https://github.com/PyGithub/PyGithub/blob/master/github/MainClass.py#L112
  github:
    - base_url: https://github.com/iilei/pairing_matrix.git
      login_or_token: '{{ .Env.ACCESS_TOKEN_GITHUB }}'
  # gitlab repositories options - see https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/__init__.py#L51
  # gitlab:
  #  - base_url: ...
  #    access_token: '{{ .Env.ACCESS_TOKEN_GITLAB }}'
